# 'https://viyar.ua/excel_export/?id=2559&to_xls=Y&lang=ua',
# 'https://viyar.ua/excel_export/?id=2530&to_xls=Y&lang=ua',
url_list = ['https://viyar.ua/excel_export/?id=2562&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=3277&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2544&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2561&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2560&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2545&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2537&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2990&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2536&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2535&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2533&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2532&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2531&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2522&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2575&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2572&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2571&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=3231&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2568&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2565&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2898&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2579&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2578&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2577&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2576&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2573&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2980&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=3208&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=3202&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2582&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2581&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2580&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=3069&to_xls=Y&lang=ua',
            'https://viyar.ua/excel_export/?id=2585&to_xls=Y&lang=ua'
            ]

