# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'img_viwer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_viwer(object):
    def setupUi(self, Form_viwer):
        Form_viwer.setObjectName("Form_viwer")
        Form_viwer.resize(1204, 803)
        self.gridLayoutWidget = QtWidgets.QWidget(Form_viwer)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 1181, 781))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_down = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_down.setObjectName("pushButton_down")
        self.verticalLayout.addWidget(self.pushButton_down)
        self.pushButton_up = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_up.setObjectName("pushButton_up")
        self.verticalLayout.addWidget(self.pushButton_up)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 10)
        self.gridLayout.setRowStretch(0, 100)

        self.retranslateUi(Form_viwer)
        QtCore.QMetaObject.connectSlotsByName(Form_viwer)

    def retranslateUi(self, Form_viwer):
        _translate = QtCore.QCoreApplication.translate
        Form_viwer.setWindowTitle(_translate("Form_viwer", "Перегляд зображення"))
        self.pushButton_down.setText(_translate("Form_viwer", "<"))
        self.pushButton_up.setText(_translate("Form_viwer", ">"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_viwer = QtWidgets.QWidget()
    ui = Ui_Form_viwer()
    ui.setupUi(Form_viwer)
    Form_viwer.show()
    sys.exit(app.exec_())
